### ISSUE TITLE
Appears to be a problem with ROOT versions >=6.14

### ISSUE THREAD

**Issue by matthewkenzie** [gammacombo/gammacombo#177] opened 2019-08-20 15:38 UTC
Found some issue with the datasets scanning with ROOT versions >=6.14. Rolling back to 6.08 will resolve this. Still to be understood exactly what the problem and to be reported to ROOT people.

**Comment by tmombaecher** [comment] 2020-02-06 14:13
The problem becomes clearer:
When reading the dataset, fitmodel and constraints from a RooWorkspace and trying to fit it again with `pdf->fitTo( *dataToFit, RooFit::Save() , RooFit::ExternalConstraints(*this->getWorkspace()->set(constraintName)), RooFit::Extended(kTRUE))`  (https://github.com/gammacombo/gammacombo/blob/master/core/src/PDF_Datasets.cpp#302), the constraints are ignored and the fit gives nonsensical results

**Comment by tmombaecher** [comment] 2020-02-06 14:13
The problem becomes clearer:
When reading the dataset, fitmodel and constraints from a RooWorkspace and trying to fit it again with `pdf->fitTo( *dataToFit, RooFit::Save() , RooFit::ExternalConstraints(*this->getWorkspace()->set(constraintName)), RooFit::Extended(kTRUE))`  (https://github.com/gammacombo/gammacombo/blob/master/core/src/PDF_Datasets.cpp#302), the constraints are ignored and the fit gives nonsensical results

**Comment by tmombaecher** [comment] 2020-02-19 16:24
I can confirm that it's because somehow RooFit cannot combine constraints and pdf coming from the same RooWorkspace. If I make a copy of the pdf and then try to refit, it works. While fixing the bug for GammaCombo, I will submit a bug report to ROOT with a minimal working example. @matthewkenzie: Can you confirm that it appears from version 6.14 on?

**Comment by tmombaecher** [comment] 2020-02-19 17:14
Hm, I cannot reproduce it in a minimal python example...

**Comment by matthewkenzie** [comment] 2020-02-19 20:50
Can’t confirm the exact version but I certainly first saw it when moving from 6.08 -> 6.14 (I think)

**Comment by tmombaecher** [comment] 2020-02-20 14:24
The bug is fixed in #197. The origin is a ROOT "feature" rather than a bug:
When you run `RooAbsPdf::createNll()`, ROOT will somehow cache the NLL once computed and reuse it when it is needed the next time. In the initialisation of the `PDF_Datasets` class we were also initialising the `minNll` value by running `RooAbsPdf::createNll()`, but without specifying the constraints. Thus the constraints were lost for the fits.

**Comment by matthewkenzie** [comment] 2020-02-20 14:52
Oh great job. Guess we should make a new release for this? Are we at v1.4 now?

**Comment by tmombaecher** [comment] 2020-02-20 15:00
I am a bit hesitant to make a new release every week...
On the other hand it's a bug fix (though the bug appears only for newer ROOT versions).
My idea would still be to wait till summer (unless there's something really pressing) and merge it only into the development branch for now.
By then I should have a few more features in terms of debug plots and configurability that was requested in a RD meeting.

But if you think it's better to make this a new release, do so.

**Comment by matthewkenzie** [comment] 2020-02-20 16:21
I agree having a new release every 5 mins isn’t ideal but this is a genuine bug fix rather than a development feature.

**Comment by tmombaecher** [comment] 2020-02-27 12:23
apparently there are other problems popping up still, so let's wait a bit. I'm happy that Fionn pointed the issue out.

**Comment by matthewkenzie** [comment] 2020-04-15 22:40
Can this now be closed?

**Comment by tmombaecher** [comment] 2020-04-16 05:35
I have not heard any more from Radha, so I would think also his error is fixed. Yes.

**Closed by tmombaecher** 2020-04-16 05:35 UTC
Labels: bug
