### ISSUE TITLE
Refitting with different starting values after applying physical range

### ISSUE THREAD

**Issue by fionnbishop** [gammacombo/gammacombo#215] opened 2020-06-11 15:11 UTC
I have spotted two potential bugs. Firstly, I get a segmentation violation, I believe when reaching line 1697 of MethodDatasetsPluginScan. This is when the poi is fixed to its minimum physical value due to being outside the prange, and then the test stat is negative, and then there is no improvement with different starting values (so only when the fit is really struggling!)

https://github.com/gammacombo/gammacombo/blob/3d43b971a211ade23e83a2612dd73ec516e37362/core/src/MethodDatasetsPluginScan.cpp#L1697

I assume what happens is the code tries to find the poi in the floating parameters of r1, which it can't do, because it is fixed in r1. Relevant part of log file:

```
1692 DEBUG in MethodDatasetsPluginScan::scan1d_plugin() - perform free toy fit
1693 Setting toy back as data 0x555cdcd08280
1694 ----> problem in current fit: going to refit with strategy 0 , summary:
1695 ----> NLL value: 8439.33984
1696 ----> fit status: -13
1697 ----> dChi2: -0.119140625
1698 ----> dChi2PDF: -0.119140625
1699 ----> free fit has status 0 but creates a negative test statistic
1700 ----> dChi2: -0.119140625
1701 ----> scan fit min nll:8439.28027
1702 ----> free fit min nll:8439.33984
1703 ----> refit with strategy: 1
1704 MethodDatasetsPluginScan::scan1d()::fit f_Br_ratio_Bc_2015_16_17_18_Bc2DpstDz_DzPp_WS_24_Bcfr_Bcpr_Bp_Bcmass_MCstat_bkg_sgD_BrDst=-1.02676569 out of physics range, fixing to      0
1705 ----> problem in current fit: going to refit with strategy 0 , summary:
1706 ----> NLL value: 8439.15234
1707 ----> fit status: 4
1708 ----> dChi2: 0.255859375
1709 ----> dChi2PDF: 0.255859375
1710 -----> unknown / fitResult neg test stat, but status4
1711 ----> refit with strategy: 1
1712 ----> problem in current fit: going to refit with strategy 1 , summary:
1713 ----> NLL value: 8439.38379
1714 ----> fit status: -13
1715 ----> dChi2: -0.20703125
1716 ----> dChi2PDF: -0.20703125
1717 ----> free fit has status 0 but creates a negative test statistic
1718 ----> dChi2: -0.20703125
1719 ----> scan fit min nll:8439.28027
1720 ----> free fit min nll:8439.38379
1721 ----> refit with strategy: 2
1722 ----> too large edm
1723 ----> edm: 1.98255809
1724 ----> problem in current fit: going to refit with strategy 2 , summary:
1725 ----> NLL value: 8439.32422
1726 ----> fit status: -100
1727 ----> dChi2: -0.087890625
1728 ----> dChi2PDF: -0.087890625
1729 -----> unknown / fitResult neg test stat, but status-100
1730 +++++ > still negative test statistic after whole procedure!!
1731 +++++ > try to fit with different starting values
1732 +++++ > dChi2: -0.087890625
1733 +++++ > dChi2PDF: -0.087890625
1734 +++++ > no Improvement found, reset ws par value to last fit result
1735
1736  *** Break *** segmentation violation
```

Second point, which I am less sure about: ParameterToScan is set not-constant prior to refitting with different starting values (which affects r_tmp), when I believe it should still be set to its minimum physical value.

https://github.com/gammacombo/gammacombo/blob/3d43b971a211ade23e83a2612dd73ec516e37362/core/src/MethodDatasetsPluginScan.cpp#L1682

**Comment by tmombaecher** [comment] 2020-06-15 09:42
Sorry for answering so late:
indeed these lines can probably introduce the SegFault you describe (copy-paste error, I'm sorry) and were probably even introducing a misbehaviour for those cases. I committed a fix in #216. But I currently have no way to check (no "problematic" case at hand quickly). Let us know whether the fix works as intended.

**Comment by fionnbishop** [comment] 2020-06-23 10:52
This works as far as I can tell - Thanks for making the fix.

**Comment by tmombaecher** [comment] 2020-06-29 06:16
Thanks for the check! closing this then.

**Closed by tmombaecher** 2020-06-29 06:16 UTC
