### ISSUE TITLE
Problem with interval extraction for PLUGIN scan

### ISSUE THREAD

**Issue by matthewkenzie** [gammacombo/gammacombo#228] opened 2020-10-13 11:40 UTC
I'm seeing a weird little bug which is that the new CL interval maker is doing something very fishy for plugin scans. Look at the plot below in which it clearly finds the wrong upper value for the estimate.

@tmombaecher do you have an idea what can cause that?

![gammacharm_empty+101+152+107_g_plugin](https://user-images.githubusercontent.com/1140576/95855998-41a86880-0d51-11eb-8e88-0e05370492de.png)

**Comment by tmombaecher** [comment] 2020-10-13 12:09
Hm, so it's the new CL interval maker, i.e. the one you have to choose with a `-qh` option?
I think I have not looked at this part of the code yet.
Just guessing:
it might be an issue with starting values combined with the interpolation fit.
For the default CL maker code I had some months ago added also fit point uncertaintie to the interpolation. But that worked very well (and you seem to use the other method here). I would therefore check
a) starting values
b) interpolation fits (you might already get them with the `--controlplots` option, at least I added the plots for the default case some months ago)
d) the amount of points taken into account in the interpolation.
Unfortunately I am off for the next days and can only take a look really next week.

**Comment by tmombaecher** [comment] 2020-10-13 12:11
do you have a command to reproduce the error?

**Comment by matthewkenzie** [comment] 2020-10-13 12:13
Ah no it's not done with a `--qh` command so perhaps it doesn't use the new maker? Let me try and look into a bit more and see if I can provide something which will reproduce it.

**Comment by tmombaecher** [comment] 2020-10-19 12:49
I found a way to reproduce and corner the error. It seems related to the quadratic interpolation (independent of the new `CLIntervalMaker` or the standard `interpolate()` method in the `MethodAbsScan` class) at a low number of scan points.
It's not unproblematic, as it does not converge with a high number of toys. I suspect that for few scan points the interpolation uses points including both flanks of the peak, which leads to a bad fit.

Command to reproduce:
`bin/tutorial -c 1 --var a_gaus --npoints 26 --ntoys 1000 --ps 1 --npointstoy 26 --scanrange -7.0:7.0 -a plugin`
![tutorial_tutorial1_a_gaus_plugin](https://user-images.githubusercontent.com/22791577/96452998-28ecf680-121a-11eb-9553-bb367ee1477e.png)

**Comment by tmombaecher** [comment] 2020-10-20 10:56
Found a solution. The interpolation fit was not working because the start parameters were not set properly. 
Redefining the quadratic function as interpolation around the scan point close to the interval boundary and choosing starting values with a linear function before seems to work (for 2 very different examples).
Testing a bit more the datasets case before ready to merge.
![tutorial_dataset_branchingRatio_plugin](https://user-images.githubusercontent.com/22791577/96577152-84c78600-12d3-11eb-9eb2-2baead8157d6.png)
![tutorial_tutorial1_a_gaus_plugin](https://user-images.githubusercontent.com/22791577/96577156-85601c80-12d3-11eb-8fc0-1eab94c98404.png)

**Comment by tmombaecher** [comment] 2020-10-21 07:02
I merged the fix and consider this solved. ✅

**Closed by tmombaecher** 2020-10-21 07:02 UTC
Labels: bug

**Comment by matthewkenzie** [comment] 2020-10-21 07:30
Thanks @tmombaecher !
